import React from 'react';
import './ExplainModal.css';

const ExplainModal = ({ isOpen, onClose, explanation, loading, error }) => {
  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content explain-modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <h3>📚 Chart Explanation</h3>
          <button className="modal-close" onClick={onClose}>
            ×
          </button>
        </div>
        <div className="modal-body">
          {loading && (
            <div className="loading-state">
              <div className="loading-spinner"></div>
              <p>🤖 AI is analyzing the chart...</p>
            </div>
          )}
          
          {error && (
            <div className="error-state">
              <p className="error-message">❌ {error}</p>
              <button onClick={() => window.location.reload()} className="retry-button">
                Try Again
              </button>
            </div>
          )}
          
          {explanation && !loading && (
            <div className="explanation-content">
              <div className="explanation-text">
                {explanation.split('\n').map((line, index) => (
                  <p key={index}>{line}</p>
                ))}
              </div>
              <div className="explanation-footer">
                <small>
                  💡 This explanation is generated by AI for educational purposes. 
                  Always do your own research before making investment decisions.
                </small>
              </div>
            </div>
          )}
        </div>
        
        {!loading && (
          <div className="modal-footer">
            <button onClick={onClose} className="close-button">
              Got it! 👍
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default ExplainModal;
